### ISSUE TITLE
Stats parameter not working

### ISSUE THREAD

**Issue by anhchungite** [keepacom/php_api#11]
I used:

- &stats=180
- &stats=2017-07-01,2017-07-31 

And response  of all case has csv array with records from year 2015, 2016, 2017, 2018.
I think stats parameter not working.

My request url: 

> https://api.keepa.com/product/?key=XXXXXXXX&asin=B00ZEYGBRI&domain=1&update=0&history=1&stats=2017-07-01,2017-07-31

**Comment by keepacom** [comment]
The stats parameter does not change the csv field. It only changes the interval for which the statistical values in the statistics objects (.stats) are calculated for.

**Comment by anhchungite** [comment]
> The stats parameter does not change the csv field. It only changes the interval for which the statistical values in the statistics objects (.stats) are calculated for.

Thanks for reply.
So it's mean csv field will be get all history data?
How to I can change the csv field? Are there any parameter for this?

**Comment by keepacom** [comment]
The csv field only be retrieved or omitted in its entirety. It can not be changed.
