### ISSUE TITLE
publicationDate, releaseDate and listedSince seem not working

### ISSUE THREAD

**Issue by anhchungite** [keepacom/php_api#12]
I have requested API for get info ASINs: `B0148DA4J6,B018RXDYD6,B0148DA52M,B0148DA46O,B014QMIFGI,B014QMIFEU.`
But in results, `publicationDate`,  `releaseDate` and `listedSince` equals -1.

In `publicationDate`, `releaseDate `and `listedSince`, where is the selling date? Because docs API description somewhat ambiguously.

**Comment by keepacom** [comment]
publicationDate and releaseDate are -1 then those fields are not set on the Amazon listing. Many product groups do not have either a publication date or a release date. We can not always provide a listedSince date, as described in the documentation.

Not sure what you mean by selling date? If you want to know when the product was first offered/listed on Amazon you have check the listedSince (if available).

**Comment by anhchungite** [comment]
Thanks for reply,
I have understand.
