### ISSUE TITLE
The example is of no use

### ISSUE THREAD

**Issue by Shamim1977** [keepacom/php_api#14]
Hi, my client is a paid user.
I installed it in my mac with composer and then put everything under vendor to my web domain. Now I am calling it this way, but it seems something is broken somewhere.

    use Keepa\API\Request;
    use Keepa\API\ResponseStatus;
    use Keepa\helper\CSVType;
    use Keepa\helper\CSVTypeWrapper;
    use Keepa\helper\KeepaTime;
    use Keepa\helper\ProductAnalyzer;
    use Keepa\helper\ProductType;
    use Keepa\KeepaAPI;
    use Keepa\objects\AmazonLocale;

    require_once ('../keepa/autoload.php'); //this path is correct, no doubt

$keepakey = 'my-long-api-key'; //not disclosing here, obviously.
$api = new KeepaAPI($keepakey);
    $r = Request::getProductRequest(AmazonLocale::US, 0, "2019-01-01", "2019-03-13", 0, true, 'B0792BSRTW');

    $response = $api->sendRequestWithRetry($r);

    switch ($response->status) {
        case ResponseStatus::OK:
            // iterate over received product information
            foreach ($response->products as $product){
                if ($product->productType == ProductType::STANDARD || $product->productType == ProductType::DOWNLOADABLE) {

                    //get basic data of product and print to stdout
                    $currentAmazonPrice = ProductAnalyzer::getLast($product->csv[CSVType::AMAZON], CSVTypeWrapper::getCSVTypeFromIndex(CSVType::AMAZON));

                    //check if the product is in stock -1 -> out of stock
                    if ($currentAmazonPrice == -1) {
                        echo sprintf("%s %s is currently not sold by Amazon (out of stock) %s",$product->asin,$product->title,PHP_EOL);
                    } else {
                        echo sprintf("%s %s Current Amazon Price: %s %s",$product->asin,$product->title,$currentAmazonPrice,PHP_EOL);
                    }

                    // get weighted mean of the last 90 days for Amazon
                    $weightedMean90days = ProductAnalyzer::calcWeightedMean($product->csv[CSVType::AMAZON], KeepaTime::nowMinutes(),90, CSVTypeWrapper::getCSVTypeFromIndex(CSVType::AMAZON));

                } else {
                    //none
                }
            }
            break;
        default:
            print_r($response);
    }

What's wrong?

**Comment by keepacom** [comment]
Hello,

Prob. your require once is wrong, needs to be in the same folder, not one above.

Anyways github is for framework code related issues.

Please understand that we dont provide any programming support.
