### ISSUE TITLE
Retrieve Token Status

### ISSUE THREAD

**Issue by MinsooJ** [keepacom/php_api#16]
Can you create a function to retrieve token status in Request? 
   
 public static function getTokenStatusRequest()
    {
        $r = new Request();
        $r->path = "token";
        return $r;
    }

**Comment by keepacom** [comment]
Can you create a pull request for it?

Also cover it with a test please.

Otherwise theres a way of dynamic building your own Request as well as the token information is provided for every request you did.

**Comment by MinsooJ** [comment]
like you said I customized path -> "token"
        $r = Request::getCategorySearchRequest(null,null,null);
        $r->path = "token";
        $r->parameter = null;
        $response = $api->sendRequestWithRetry($r);
        $tokensLeft = $response->tokensLeft;

It works like this but I will also create a pull request. This is might be useful if we have to check the current token status before making an actual request. I had an issue when running constant requests.

**Comment by saschaarthur** [comment]
Hello,

if youre using sendRequestWithRetry you dont have to care about anything, it blocks until the data is received, anyways we will merge your request asap, thanks for it.

**Comment by keepacom** [comment]
its included in 1.40.2
