### ISSUE TITLE
Uncaught Error: Class 'Keepa\KeepaAPI' not found

### ISSUE THREAD

**Issue by rakeshdonga** [keepacom/php_api#18]
i have run below command run like 

`composer require keepa/php_api:*`

but still below error showing 

> Fatal error: Uncaught Error: Class 'Keepa\KeepaAPI' not found in
> /keepaapi/php_api/index.php:15 Stack
> trace: #0 {main} thrown in
> /keepaapi/php_api/index.php on line 15

and **my root directory folder structure**

[![http://prntscr.com/o7qyct][1]][1]

  [1]: https://i.stack.imgur.com/lOje5.png

my code is 

    <?php
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
    
    use Keepa\API\Request;
    use Keepa\API\ResponseStatus;
    use Keepa\helper\CSVType;
    use Keepa\helper\CSVTypeWrapper;
    use Keepa\helper\KeepaTime;
    use Keepa\helper\ProductAnalyzer;
    use Keepa\helper\ProductType;
    use Keepa\KeepaAPI;
    use Keepa\objects\AmazonLocale;
    
    $api = new KeepaAPI("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    $r = Request::getProductRequest(AmazonLocale::DE, 0, "2015-12-31", "2018-01-01", 0, true, ['B001G73S50']);
    
    $response = $api->sendRequestWithRetry($r);
    
    switch ($response->status) {
    	case ResponseStatus::OK:
    		// iterate over received product information
    		foreach ($response->products as $product){
    			if ($product->productType == ProductType::STANDARD || $product->productType == ProductType::DOWNLOADABLE) {
    
    				//get basic data of product and print to stdout
    				$currentAmazonPrice = ProductAnalyzer::getLast($product->csv[CSVType::AMAZON], CSVTypeWrapper::getCSVTypeFromIndex(CSVType::AMAZON));
    
    				//check if the product is in stock -1 -> out of stock
    				if ($currentAmazonPrice == -1) {
    					echo sprintf("%s %s is currently not sold by Amazon (out of stock) %s",$product->asin,$product->title,PHP_EOL);
    				} else {
    					echo sprintf("%s %s Current Amazon Price: %s %s",$product->asin,$product->title,$currentAmazonPrice,PHP_EOL);
    				}
    
    				// get weighted mean of the last 90 days for Amazon
    				$weightedMean90days = ProductAnalyzer::calcWeightedMean($product->csv[CSVType::AMAZON], KeepaTime::nowMinutes(),90, CSVTypeWrapper::getCSVTypeFromIndex(CSVType::AMAZON));
    
    			} else {
    
    			}
    		}
    		break;
    	default:
    		print_r($response);
    }

**Comment by keepacom** [comment]
Hello,

We dont provide any coding support, please dont create threads in the section because its only for code related issues.

Anways seems that you dont use a framework so you need to uncomment the require_once section:

```
/* maybe required - depends if youre using a framework which automaticly loading this file
require_once "vendor/autoload.php";
*/ 
```
