### ISSUE TITLE
Item dimensions seem to be missing when using this php api

### ISSUE THREAD

**Issue by woodymendoza** [keepacom/php_api#20]
Item dimensions seem to be missing when using this php api.

when I go to the api directly
https://api.keepa.com/product/?key=ADDAPIKEY&asin=B01LTHP2ZK&domain=1&update=0&history=0&stats=2019-08-05%2C2019-09-04

I get these fields 

``
"itemHeight": 295,
"itemLength": 356,
"itemWidth": 137,
"itemWeight": 1701,
``

**However** when I call it via this **PHP API** I do not.

https://github.com/keepacom/php_api/blob/master/src/objects/Product.php 
looks like, itemHeight, itemLength, itemWidth, itemWeight are missing from here.

**Comment by keepacom** [comment]
solved in 1.40.3
