### ISSUE TITLE
Minor update :)

### ISSUE THREAD

**Issue by ReyazBeigh** [keepacom/php_api#21]
https://github.com/keepacom/php_api/blob/d94b1d4b8544aa4e33118e71059544702f1e7953/src/API/Request.php#L196

        if(!empty($asins))
            $r->parameter["asin"] = implode(",", $asins);

Needed to do small addition here, works when we need to get product info from other ids, than ASIN otherwise all good, Thank you!

**Comment by saschaarthur** [comment]
fixed in 1.44, sorry for the late response :)
