### ISSUE TITLE
Keepa Locale for Amazon AU

### ISSUE THREAD

**Issue by gokigoks** [keepacom/php_api#22]
Hello,

As I was using 12 as the keepa locale value for Amazon AU, I did not get results. On digging through Keepa.com's forums I saw a discussion with a user using 13 as the value for AU locale. 

I just wanted to get clarification if the correct value for Amazon AU in keepa APi. Thank you very much.

**Comment by saschaarthur** [comment]
Thanks for reporting, corrected in 5d4e42e / 1.43.1 , AU has ID 13.
