### ISSUE TITLE
Deprecated method is used by one of dependencies

### ISSUE THREAD

**Issue by egorix** [keepacom/php_api#23]
Here's what the error appears on PHP 7.4.7:

"class": "ErrorException",
"message": "Array and string offset access syntax with curly braces is deprecated",
"code": 0,
"file": "/home/dh/www/vendor/netresearch/jsonmapper/src/JsonMapper.php:280",

I guess verion 0.11 is too old for JsonMapper. It's 2016 year. Need to upgrade!

**Comment by keepacom** [comment]
Thanks for reporting

Its solved it in SDK 2.0.0, which we released just now.
