### ISSUE TITLE
How can i know that user is prime user or not.

### ISSUE THREAD

**Issue by RuchitaCrawl** [keepacom/php_api#26]
Hey :)

 I want to know that is user is prime user or not. can you provide some details about it with product data?

Can you say how to calculate review and sales rank count?

**Comment by keepacom** [comment]
For the buy box access the [statistics object's](https://discuss.keepa.com/t/statistics-object/1308?u=keepa) _buyBoxIsPrimeEligible_ field.
For all other offers check the isPrime field of the [marketplace offer object](https://discuss.keepa.com/t/marketplace-offer-object/807?u=keepa). 

Please refer to the documentation on how to access those objects.
