### ISSUE TITLE
Keepa Get all products with a given keywords for example ペット消臭スプレー 

### ISSUE THREAD

**Issue by hubdevpro** [keepacom/php_api#27]
Locale working for me and all methods related to Request i tried but not getting the desired result , ペット消臭スプレー] this keyword have 2k products and i want to fatch them all , is there any way ...? or any custom query or any example , your provided example is not a kind of standard example

**Comment by keepacom** [comment]
Our product search is limited to 100 results. Our product finder only searches the product title but can provide up to 10.000 results.

**Comment by hubdevpro** [comment]
ok so if i retrieve asinlist from a given title then can i use your any method which provide me desire result for example for now i stored all asinglist in a array format then i passed it to Request::getProductRequest(AmazonLocale::JP, 0, "", "", 0, true, $data); using foreach loop but this is also have limitation with per page records , page

**Comment by hubdevpro** [comment]
for example i set page to 0 then paer page =50 , from frontend i sent a request where page=2 per page 50 results . but getting the same result  can you guide me please

**Comment by saschaarthur** [comment]
Is this still a problem? 
Do you have example code which proofs that this is an issue of our API-Framework?

Otherwise we will close the issue within the next 48 hours.
