### ISSUE TITLE
Keepa domain numbers 

### ISSUE THREAD

**Issue by gokigoks** [keepacom/php_api#29]
Hi,

I'm trying to send a request to the netherlands but im getting an invalid domain message.

`[error] => Keepa\API\KeepaRequestError Object
        (
            [type] => invalidParameter
            [message] => You used an invalid parameter for this API Call.
            [details] => [{"type":"domain","message":"invalid"}]
        )
`
My request has these values  for parameters. 

`(
            [parameter] => Array
                (
                    [asin] => B01M5CJWSH,B06Y32PXNL
                    [domain] => 14
                    [update] => 0
                    [history] => 1
                    [rating] => 1
                )
        )
`

Can you guys help giving insight on what my issue is?

**Comment by keepacom** [comment]
Netherlands is not supported. Please read the documentation for valid domain parameter values.

**Comment by gokigoks** [comment]
Hi,

NL is listed as domain 14 in the source code and have seen it work before. Can you confirm if its a discontinued marketplace or a temporary issue?

**Comment by keepacom** [comment]
domainId 14 was never valid. As it may be in the future it is present in the source code.
