### ISSUE TITLE
jsonMapper not found

### ISSUE THREAD

**Issue by nasarullahkhan321** [keepacom/php_api#3]
i am getting this error .Fatal error: Class 'JsonMapper' not found.kindly tell me how to fix this issue.
i also run this command in the project root directory.composer require keepa/php_api

**Comment by keepacom** [comment]
Hello,

Which version youre running? Can you please try to upgrade to 1.12?

**Comment by nasarullahkhan321** [comment]
i dont understand your point which thing i upgrade..i just download the Keepa.com API PHP Framework from this link https://github.com/keepacom/php_api..and then i run the command "composer require keepa/php_api"..but when i run this project each and everything is fine but there is only one error ..Fatal error: Class 'JsonMapper' not found..
tell me how can i fix this issue..and also send me the link from where i can upgrade it to 1.12

**Comment by nasarullahkhan321** [comment]
i have upgrade it to 1.12 but the error is still same Class JsonMapper not found..
kindly help me how can i resolve this issue

**Comment by keepacom** [comment]
did you run composer install? to fetch the dependencies?

**Comment by nasarullahkhan321** [comment]
yes i have run the composer

**Comment by keepacom** [comment]
you using any framework? if not did you include the vendor/autoload.php?

**Comment by nasarullahkhan321** [comment]
i am using laravel framework

**Comment by keepacom** [comment]
can you post your output of:
"composer install"
and maybe your composer.lock file?
We tried it with laravel and it works for us.

**Comment by liangdabiao** [comment]
please help me ,the php sdk can not work well. because there is no csv return. thanks

**Comment by keepacom** [comment]
@liangdabiao 
the SDK does not support writing csv out of the box. (its using php objects for further data handling)

You can use this function (http://php.net/manual/de/function.fputcsv.php) to write your objects to a csv file.

**Comment by keepacom** [comment]
Hello,
Maybe you meant the example which was not receiving the csv:

https://github.com/keepacom/php_api/commit/56f4ef2bdb5d25e1ec4905046137ebc6d1e6a40b

this could help you out, otherwise this issue is closed
