### ISSUE TITLE
How use mustHaveAmazonOffer json parameter in DealRequest() istance?

### ISSUE THREAD

**Issue by annuncispot** [keepacom/php_api#32]
Hi,

how can use "mustHaveAmazonOffer" json parameter when i read a new DealRequest() istance?

Thanks

**Comment by saschaarthur** [comment]
Hello, 

This Issue section here is only for Framework issues, please dont open issues here.

In generall we dont give any coding support, but you have trouble about specific requests, feel free to open the question in our Support Forum: 
https://keepa.com/#!discuss/
