### ISSUE TITLE
getOutOfStockPercentageInInterval parameters

### ISSUE THREAD

**Issue by mikemilano** [keepacom/php_api#36]
I'm trying to get the 90 day Amazon Out Of Stock rate for a product.

I've been successful with other ProductAnalyzer methods, but the parameters documented for `getOutOfStockPercentageInInterval` are not very clear.

Could someone explain what "keepa time minutes" are as they relate to this method? (Or link me to documentation if it exists)

An example would go a long way for this one.

Here is the related except from https://github.com/keepacom/php_api/blob/5187dc48ba616607888057e7b963ea3d7511e1f5/src/helper/ProductAnalyzer.php#L432
```
 /**
     * Returns a the percentage of time in the given interval the price type was out of stock
     *
     * @param $csv int[] value/price history csv
     * @param $now int current keepa time minutes
     * @param $start int start of the interval (keepa time minutes), can be 0.
     * @param $end int end of the interval (keepa time minutes), can be in the future (Integer.MAX_VALUE).
     * @param $type CSVType  the type of the csv data.
     * @param $trackingSince int the product object's trackingSince value
     * @return int percentage between 0 and 100 or -1 if insufficient data. 100 = 100% out of stock in the interval.
     */
    public static function getOutOfStockPercentageInInterval($csv, $now, $start, $end, CSVType $type, $trackingSince)
   ...
```

Any insight would be greatly appreciated. Thank you!

**Comment by keepacom** [comment]
> Keepa Time minutes
Time format used for all timestamps. To convert to an uncompressed timestamp (Unix epoch time), add 21564000 and then multiply by 60000 (for milliseconds, or 60 for seconds).

You can use [this class](https://github.com/keepacom/php_api/blob/master/src/helper/KeepaTime.php) to get the `KeepaTime.nowMinutes()`.

**Comment by mikemilano** [comment]
Thanks for that! Regarding the other parameters, could you give me a sanity check on how I'm using this?

I'm getting a result of `-1` and suspect it's because the use of `CVSType` is different than other ProductAnalyzer methods. (I don't think I'm constructing it correctly)

The ASIN is a product that should be 100% OOS for Amazon.

```
// Just showing as an example of how I am getting $product
$r = Request::getProductRequest(AmazonLocale::US, 20, null, null, 0, true, ['B082FGH4MQ']);
$response = $this->api->sendRequestWithRetry($r);
$product = $response->products[0];

// Setup arguments for getOutOfStockPercentageInInterval()
$now = KeepaTime::nowMinutes();
$start = strtotime('-90 days') + KeepaTIME::keepaStartMinute * 60;
$end = $now;

$cvsType = new CSVType(CSVType::AMAZON, true, false, false, false);
$result = ProductAnalyzer::getOutOfStockPercentageInInterval($product->csv[CSVType::AMAZON], $now, $start, $end, $cvsType, $product->trackingSince);
```

Result is `-1` but I am expecting `100`.

**Comment by keepacom** [comment]
You can just use the [Statistics Object](https://discuss.keepa.com/t/statistics-object/1308) (accessible with the _stats_ parameter). 

We do not provide programming support.

**Comment by mikemilano** [comment]
Wow, the Statistics Object has everything I need. Thank you.
