### ISSUE TITLE
JSONMAPPER not found ..how we can upgrade it to 1.12.

### ISSUE THREAD

**Issue by nasarullahkhan321** [keepacom/php_api#4]
i dont understand your point which thing i upgrade..i just download the Keepa.com API PHP Framework from this link https://github.com/keepacom/php_api..and then i run the command "composer require keepa/php_api"..but when i run this project each and everything is fine but there is only one error ..Fatal error: Class 'JsonMapper' not found..
tell me how can i fix this issue..and also send me the link from where i can upgrade it to 1.12

**Comment by keepacom** [comment]
Hello please stick to this thread #3 closed duplicate
