### ISSUE TITLE
buyBoxStats wrong data

### ISSUE THREAD

**Issue by linquant** [keepacom/php_api#40]
Hello,

I have an wrong data to fields buyBoxStats. On the documentation, we attempt to get :

![image](https://github.com/keepacom/php_api/assets/6512186/034cff6b-698b-47d6-a969-199b6879016d)

But i have got 
![image](https://github.com/keepacom/php_api/assets/6512186/ff222345-0abb-4103-8c4f-6797da15f840)

**Comment by saschaarthur** [comment]
Thank you, youre completly right. 

Wondering how nobody realized this till now..

Its fixed in 2.0.11.
