### ISSUE TITLE
version 1.12 is also giving me the same error class JsonMapper not found..how can i fix it?? 

### ISSUE THREAD

**Issue by nasarullahkhan321** [keepacom/php_api#5]
i have update it to 1.12 but still the error is same .Fatal error: Class 'JsonMapper' not found ..i have download the 1.12 version from this link https://github.com/keepacom/php_api/releases...
how can i fix this isssue ??????????????????????

**Comment by keepacom** [comment]
Hello please stick to this thread #3 closed duplicate
