### ISSUE TITLE
i am not getting the product price after keepa API request 

### ISSUE THREAD

**Issue by nasarullahkhan** [keepacom/php_api#6]
i am using keepa API to get the product information.i am getting all the information about specific ASIN.but the problem is that i am not getting the product price.
suppose i am getting the information of this ASIN B00YV9Y92Q .https://www.amazon.com/dp/B00YV9Y92Q?psc=1 . the price of this product is $600 i am getting all the information of this product but i am not getting the price.
this is the array which i am getting after keepa request 
asin
title 
manufacturer 
type 
productGroup 
model 
color 
size
lastUpdate
lastPriceChange
rootCategory
productType
parentAsin
domainId
hasReviews
ean
upc
mpn
trackingSince
brand
label
department
publisher
partNumber
studio
packageHeight
packageLength
packageWidth
packageWeight
packageQuantity
lastRatingUpdate
binding
i am getting each and every thing about the product but i am not getting the price ..
kindly help me to resolve this issue how i can get the price of product

**Comment by nasarullahkhan** [comment]
Kindly help me how i can get the product price.how i can resolve this issues

**Comment by keepacom** [comment]
hello,

if you used the example you should update the request line according to this commit:

https://github.com/keepacom/php_api/commit/56f4ef2bdb5d25e1ec4905046137ebc6d1e6a40b

if this is not your issue, can you please post the full code youre using (except your api key)?
