### ISSUE TITLE
$product array did not give me the price

### ISSUE THREAD

**Issue by nasarullahkhan** [keepacom/php_api#7]
<?php
/*use Keepa\API\Request;
use Keepa\API\ResponseStatus;
use Keepa\helper\CSVType;
use Keepa\helper\CSVTypeWrapper;
use Keepa\helper\KeepaTime;
use Keepa\helper\ProductAnalyzer;
use Keepa\helper\ProductType;
use Keepa\KeepaAPI;
use Keepa\objects\AmazonLocale;

$api = new KeepaAPI("9lqvbl873ut8gunfses6j7g52nl61easq5am1i7ir2ocea09t5m097ptur7pte67");
$r = Request::getProductRequest(AmazonLocale::DE, 0, "2015-12-31", "2018-01-01", 0, false, ['B00YV9Y92Q']);

$response = $api->sendRequestWithRetry($r);

switch ($response->status) {
    case ResponseStatus::OK:
        // iterate over received product information
        foreach ($response->products as $product) {
            if ($product->productType == ProductType::STANDARD || $product->productType == ProductType::DOWNLOADABLE) {

                //get basic data of product and print to stdout
                $currentAmazonPrice = ProductAnalyzer::getLast($product->csv[CSVType::AMAZON], CSVTypeWrapper::getCSVTypeFromIndex(CSVType::AMAZON));
                                 //this give me everytime -1 when i insert any new ASIN $currentAmazonPrice = -1

//                check if the product is in stock -1 -> out of stock
                 if ($currentAmazonPrice == -1) {
                  echo sprintf("%s %s is currently out of stock! %s",$product->asin,$product->title,PHP_EOL);
                  } else {
                  echo sprintf("%s %s Current Amazon Price: %s %s",$product->asin,$product->title,$currentAmazonPrice,PHP_EOL);
                  } 
                die();
                echo 'Product Array: ';
               echo '<pre>';
                print_r($product);
//                echo 'Product Title: '.$product->title; 
//                echo 'Product Title: '.$product->manufacturer;

                // get weighted mean of the last 90 days for Amazon
                $weightedMean90days = ProductAnalyzer::calcWeightedMean($product->csv[CSVType::AMAZON], KeepaTime::nowMinutes(), 90, CSVTypeWrapper::getCSVTypeFromIndex(CSVType::AMAZON));
            } else {
                
            }
        }
        break;
    default:
        print_r($response);
}*/

**Comment by keepacom** [comment]
please only create one issue, follow up in #6 please, closed
