### ISSUE TITLE
In the offer list - Not Getting isFBA response parameter ?

### ISSUE THREAD

**Issue by sanjaykumar2338** [keepacom/php_api#9]
https://api.keepa.com/product

Response :

   [4] => Keepa\objects\Offer Object
                (
                    [offerId] => 246
                    [lastSeen] => 3317120
                    [sellerId] => A1BEUGWV94ZVRZ
                    [offerCSV] => Array
                        (
                            [0] => 3317120
                            [1] => 828
                            [2] => 1049
                        )

                    [condition] => 1
                    [conditionComment] => 
                    [isPrime] => 
                    [isMAP] => 
                    [isShippable] => 1
                    [isAddonItem] => 
                    [isPreorder] => 
                    [isWarehouseDeal] => 
                    [isScam] => 
                    [isAmazon] => 
                    [isPrimeExcl] => 
                    [stockCSV] => Array
                        (
                            [0] => 3317120
                            [1] => 999
                        )

                )

**Comment by keepacom** [comment]
hello,

we cant reproduce your issue, which version you using?

**Comment by sanjaykumar2338** [comment]
{
	"require": {
        "keepa/php_api": "1.13.6"
    }
}


{
  "name": "keepa/php_api",
  "license": "Apache-2.0",
  "description": "API Framework for Keepa.com",
  "require": {
    "php": "^5 || ^7",
    "netresearch/jsonmapper": "^0.11.0"
  },
  "require-dev": {
    "phpunit/phpunit": "~5.7"
  },
  "autoload": {
    "psr-4": {"Keepa\\": "src/"}
  }
}


Here is my request->

https://api.keepa.com/product?key=XXXXXXXXXXXXXXXX&domain=1&asin=B000L8EEPS&stats=60&offers=60

https://prnt.sc/kggiqv - when I hit through your git lib.
https://prnt.sc/kggjn8 - when I hit though postman.

**Comment by keepacom** [comment]
Hello,

Your version is no up2date please use at least 1.36.

**Comment by sanjaykumar2338** [comment]
ok, Got it. but it's taking to much in order return response almost 30s

`<?php


require_once "vendor/autoload.php";


use Keepa\API\Request;
use Keepa\API\ResponseStatus;
use Keepa\helper\CSVType;
use Keepa\helper\CSVTypeWrapper;
use Keepa\helper\KeepaTime;
use Keepa\helper\ProductAnalyzer;
use Keepa\helper\ProductType;
use Keepa\KeepaAPI;
use Keepa\objects\AmazonLocale;

$api = new KeepaAPI("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
$r = Request::getProductRequest(AmazonLocale::US, 60, "2015-12-31", "2018-01-01", 0, true, ['B000L8EEPS']);

$response = $api->sendRequestWithRetry($r);

switch ($response->status) {
    case ResponseStatus::OK:
        print_r($response);            
	break;
	default:
	   print_r("NO found!");            
    break;	
}`
